/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Product = IDL.Variant({
  'bottle1L' : IDL.Null,
  'jar20L' : IDL.Null,
  'bottle500ml' : IDL.Null,
});
export const OrderInquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Nat,
  'phone' : IDL.Text,
  'product' : Product,
});

export const idlService = IDL.Service({
  'getAllContactSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllOrderInquiries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OrderInquiry)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitOrderInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, Product, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Product = IDL.Variant({
    'bottle1L' : IDL.Null,
    'jar20L' : IDL.Null,
    'bottle500ml' : IDL.Null,
  });
  const OrderInquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Nat,
    'phone' : IDL.Text,
    'product' : Product,
  });
  
  return IDL.Service({
    'getAllContactSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllOrderInquiries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OrderInquiry)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitOrderInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, Product, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };