/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface OrderInquiry {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'phone' : string,
  'product' : Product,
}
export type Product = { 'bottle1L' : null } |
  { 'jar20L' : null } |
  { 'bottle500ml' : null };
export type Time = bigint;
export interface _SERVICE {
  'getAllContactSubmissions' : ActorMethod<[string], Array<ContactSubmission>>,
  'getAllOrderInquiries' : ActorMethod<[string], Array<OrderInquiry>>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitOrderInquiry' : ActorMethod<
    [string, string, Product, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];